/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/page2`; params?: Router.UnknownInputParams; } | { pathname: `/resort`; params?: Router.UnknownInputParams; } | { pathname: `/test-components`; params?: Router.UnknownInputParams; } | { pathname: `/travel`; params?: Router.UnknownInputParams; } | { pathname: `/health`; params?: Router.UnknownInputParams; } | { pathname: `/../components/week5/Bmi`; params?: Router.UnknownInputParams; } | { pathname: `/../components/week5/Heartbeat`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex01`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex02`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex03`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex04`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex05`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex06`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex07`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex08`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex09`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex10`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex11`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex12`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/page2`; params?: Router.UnknownOutputParams; } | { pathname: `/resort`; params?: Router.UnknownOutputParams; } | { pathname: `/test-components`; params?: Router.UnknownOutputParams; } | { pathname: `/travel`; params?: Router.UnknownOutputParams; } | { pathname: `/health`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/week5/Bmi`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/week5/Heartbeat`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex01`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex02`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex03`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex04`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex05`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex06`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex07`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex08`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex09`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex10`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex11`; params?: Router.UnknownOutputParams; } | { pathname: `/flexbox/ex12`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/page2${`?${string}` | `#${string}` | ''}` | `/resort${`?${string}` | `#${string}` | ''}` | `/test-components${`?${string}` | `#${string}` | ''}` | `/travel${`?${string}` | `#${string}` | ''}` | `/health${`?${string}` | `#${string}` | ''}` | `/../components/week5/Bmi${`?${string}` | `#${string}` | ''}` | `/../components/week5/Heartbeat${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/flexbox/ex01${`?${string}` | `#${string}` | ''}` | `/flexbox/ex02${`?${string}` | `#${string}` | ''}` | `/flexbox/ex03${`?${string}` | `#${string}` | ''}` | `/flexbox/ex04${`?${string}` | `#${string}` | ''}` | `/flexbox/ex05${`?${string}` | `#${string}` | ''}` | `/flexbox/ex06${`?${string}` | `#${string}` | ''}` | `/flexbox/ex07${`?${string}` | `#${string}` | ''}` | `/flexbox/ex08${`?${string}` | `#${string}` | ''}` | `/flexbox/ex09${`?${string}` | `#${string}` | ''}` | `/flexbox/ex10${`?${string}` | `#${string}` | ''}` | `/flexbox/ex11${`?${string}` | `#${string}` | ''}` | `/flexbox/ex12${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/page2`; params?: Router.UnknownInputParams; } | { pathname: `/resort`; params?: Router.UnknownInputParams; } | { pathname: `/test-components`; params?: Router.UnknownInputParams; } | { pathname: `/travel`; params?: Router.UnknownInputParams; } | { pathname: `/health`; params?: Router.UnknownInputParams; } | { pathname: `/../components/week5/Bmi`; params?: Router.UnknownInputParams; } | { pathname: `/../components/week5/Heartbeat`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex01`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex02`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex03`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex04`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex05`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex06`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex07`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex08`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex09`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex10`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex11`; params?: Router.UnknownInputParams; } | { pathname: `/flexbox/ex12`; params?: Router.UnknownInputParams; };
    }
  }
}
